Configs fix
KludgeProg/ppe_django pull request #8
Opened 2017-03-04 00:41 UTC by em-torres

2017-03-04 22:29 UTC, oldani requested changes
Just a minor comment

2017-03-04 22:29 UTC, oldani commented on src/settings/base.py
> +    'rest_framework'
Missing indentention here

2017-03-04 23:49 UTC, em-torres commented
Added some additional last moment changes. Please re-confirm.

2017-03-05 23:37 UTC, oldani reviewed
Just a few suggestions

2017-03-05 23:37 UTC, oldani commented on src/settings/base.py
> +    'homepage.apps.HomepageConfig',
Try to order this or by alphabetical order or (default, third partys and your own apps) order.

2017-03-05 23:37 UTC, oldani commented on README.md
> +#PPE DJANGO
I think you  could do this better, if you want there is a short course on Udacity for writing READMES.

2017-03-06 01:28 UTC, johnny243 commented on bootstrap.sh
>  cd ../../vagrant
What is the absolute path of _vagrant_ dir? /home/vagrant? If so, you could change it to something like:

> cd ~vagrant

2017-03-06 22:40 UTC, em-torres commented
Made some additional changes.

2017-03-11 17:35 UTC, oldani approved these changes

2017-03-15 23:06 UTC, merged